<?php
/**
 * PyraStore - Automatic Installer
 * One-click installation wizard
 */

session_start();
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Security: Disable installer after successful installation
if (file_exists('install.lock')) {
    die('
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Installation Locked</title>
        <style>
            body { font-family: Arial; text-align: center; padding: 50px; background: #f5f5f5; }
            .message { background: white; padding: 40px; border-radius: 10px; max-width: 500px; margin: 0 auto; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
            h1 { color: #ef4444; }
            p { color: #666; line-height: 1.6; }
            code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; }
        </style>
    </head>
    <body>
        <div class="message">
            <h1>🔒 Installation Already Completed</h1>
            <p>The installer has been locked for security reasons.</p>
            <p>To reinstall, delete the <code>install.lock</code> file from your server.</p>
            <p><strong>Warning:</strong> Reinstalling will delete all existing data!</p>
            <br>
            <a href="index.php" style="background: #FF9900; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px;">Go to Website</a>
        </div>
    </body>
    </html>
    ');
}

$step = isset($_GET['step']) ? intval($_GET['step']) : 1;
$errors = [];
$success = [];

// Step 1: Check System Requirements
if ($step == 1) {
    $requirements = [
        'PHP Version >= 7.4' => version_compare(PHP_VERSION, '7.4.0', '>='),
        'PDO Extension' => extension_loaded('pdo'),
        'PDO MySQL Extension' => extension_loaded('pdo_mysql'),
        'JSON Extension' => extension_loaded('json'),
        'MBString Extension' => extension_loaded('mbstring'),
        'GD Extension (for images)' => extension_loaded('gd'),
    ];

    $writableDirectories = [
        'assets/uploads' => is_writable(__DIR__ . '/assets/uploads'),
        'config' => is_writable(__DIR__ . '/config'),
    ];
}

// Step 2: Database Configuration
if ($step == 2 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $dbHost = trim($_POST['db_host']);
    $dbName = trim($_POST['db_name']);
    $dbUser = trim($_POST['db_user']);
    $dbPass = $_POST['db_pass'];

    try {
        // Test connection
        $pdo = new PDO("mysql:host=$dbHost", $dbUser, $dbPass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        // Create database if not exists
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `$dbName`");

        // Import SQL file
        $sql = file_get_contents(__DIR__ . '/database.sql');

        // Remove any existing USE statements
        $sql = preg_replace('/USE\s+`?\w+`?;/i', '', $sql);

        // Split by semicolons and execute
        $statements = array_filter(array_map('trim', explode(';', $sql)));

        foreach ($statements as $statement) {
            if (!empty($statement)) {
                $pdo->exec($statement);
            }
        }

        // Save database configuration
        $configContent = "<?php
/**
 * Database Configuration
 * Auto-generated by installer
 */

define('DB_HOST', '$dbHost');
define('DB_USER', '$dbUser');
define('DB_PASS', '$dbPass');
define('DB_NAME', '$dbName');
define('DB_CHARSET', 'utf8mb4');

date_default_timezone_set('Asia/Dubai');

error_reporting(E_ALL);
ini_set('display_errors', 0); // Set to 0 in production

class Database {
    private static \$instance = null;
    private \$connection;

    private function __construct() {
        try {
            \$this->connection = new PDO(
                \"mysql:host=\" . DB_HOST . \";dbname=\" . DB_NAME . \";charset=\" . DB_CHARSET,
                DB_USER,
                DB_PASS,
                [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                    PDO::ATTR_EMULATE_PREPARES => false,
                    PDO::MYSQL_ATTR_INIT_COMMAND => \"SET NAMES utf8mb4\"
                ]
            );
        } catch(PDOException \$e) {
            die(\"Connection failed: \" . \$e->getMessage());
        }
    }

    public static function getInstance() {
        if (self::\$instance === null) {
            self::\$instance = new self();
        }
        return self::\$instance;
    }

    public function getConnection() {
        return \$this->connection;
    }

    private function __clone() {}

    public function __wakeup() {
        throw new Exception(\"Cannot unserialize singleton\");
    }
}

function getDB() {
    return Database::getInstance()->getConnection();
}
";

        file_put_contents(__DIR__ . '/config/database.php', $configContent);

        // Store in session for next step
        $_SESSION['db_configured'] = true;

        header('Location: install.php?step=3');
        exit;

    } catch (PDOException $e) {
        $errors[] = 'Database Error: ' . $e->getMessage();
    } catch (Exception $e) {
        $errors[] = 'Error: ' . $e->getMessage();
    }
}

// Step 3: Site Configuration
if ($step == 3 && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $siteUrl = rtrim(trim($_POST['site_url']), '/');
    $affiliateId = trim($_POST['affiliate_id']);
    $adminUsername = trim($_POST['admin_username']);
    $adminPassword = $_POST['admin_password'];
    $adminEmail = trim($_POST['admin_email']);

    if (empty($adminUsername) || empty($adminPassword)) {
        $errors[] = 'Admin username and password are required!';
    } else {
        try {
            require_once __DIR__ . '/config/database.php';
            $db = getDB();

            // Update settings
            $stmt = $db->prepare("UPDATE settings SET setting_value = :value WHERE setting_key = :key");

            $settings = [
                'affiliate_id' => $affiliateId,
            ];

            foreach ($settings as $key => $value) {
                $stmt->execute([':value' => $value, ':key' => $key]);
            }

            // Update admin user
            $passwordHash = password_hash($adminPassword, PASSWORD_DEFAULT);
            $stmt = $db->prepare("UPDATE admin_users SET username = :username, password = :password, email = :email WHERE id = 1");
            $stmt->execute([
                ':username' => $adminUsername,
                ':password' => $passwordHash,
                ':email' => $adminEmail
            ]);

            // Update config file with site URL
            $configFile = __DIR__ . '/config/config.php';
            $configContent = file_get_contents($configFile);
            $configContent = preg_replace(
                "/define\('SITE_URL',\s*'[^']*'\);/",
                "define('SITE_URL', '$siteUrl');",
                $configContent
            );
            file_put_contents($configFile, $configContent);

            // Create install.lock file
            file_put_contents(__DIR__ . '/install.lock', date('Y-m-d H:i:s'));

            $_SESSION['installation_complete'] = true;
            header('Location: install.php?step=4');
            exit;

        } catch (Exception $e) {
            $errors[] = 'Error: ' . $e->getMessage();
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PyraStore Installer - Step <?= $step ?></title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
        }

        .header {
            text-align: center;
            color: white;
            margin-bottom: 30px;
        }

        .header h1 {
            font-size: 42px;
            margin-bottom: 10px;
            text-shadow: 0 2px 10px rgba(0,0,0,0.2);
        }

        .header p {
            font-size: 18px;
            opacity: 0.9;
        }

        .installer-box {
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }

        .steps {
            display: flex;
            background: #f8f9fa;
            padding: 0;
        }

        .step-item {
            flex: 1;
            padding: 20px;
            text-align: center;
            position: relative;
            background: #e9ecef;
            color: #6c757d;
            font-weight: 600;
            font-size: 14px;
        }

        .step-item.active {
            background: #667eea;
            color: white;
        }

        .step-item.completed {
            background: #10b981;
            color: white;
        }

        .step-number {
            display: inline-block;
            width: 30px;
            height: 30px;
            background: rgba(255,255,255,0.3);
            border-radius: 50%;
            line-height: 30px;
            margin-bottom: 5px;
        }

        .content {
            padding: 40px;
        }

        .content h2 {
            color: #1a1a1a;
            margin-bottom: 10px;
            font-size: 28px;
        }

        .content p {
            color: #666;
            margin-bottom: 30px;
        }

        .requirements-list {
            list-style: none;
            margin-bottom: 30px;
        }

        .requirements-list li {
            padding: 15px;
            margin-bottom: 10px;
            background: #f8f9fa;
            border-radius: 8px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .status-badge {
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 12px;
            font-weight: 600;
        }

        .status-badge.success {
            background: #d1fae5;
            color: #065f46;
        }

        .status-badge.error {
            background: #fee2e2;
            color: #991b1b;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-group label {
            display: block;
            margin-bottom: 8px;
            color: #1a1a1a;
            font-weight: 600;
            font-size: 14px;
        }

        .form-group input,
        .form-group select {
            width: 100%;
            padding: 12px 15px;
            border: 2px solid #e0e0e0;
            border-radius: 8px;
            font-size: 14px;
            transition: border-color 0.3s;
        }

        .form-group input:focus,
        .form-group select:focus {
            outline: none;
            border-color: #667eea;
        }

        .form-group small {
            display: block;
            margin-top: 5px;
            color: #666;
            font-size: 12px;
        }

        .alert {
            padding: 15px 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }

        .alert-error {
            background: #fee2e2;
            color: #991b1b;
            border: 1px solid #fecaca;
        }

        .alert-success {
            background: #d1fae5;
            color: #065f46;
            border: 1px solid #a7f3d0;
        }

        .alert-warning {
            background: #fef3c7;
            color: #92400e;
            border: 1px solid #fde68a;
        }

        .btn {
            padding: 14px 30px;
            border: none;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
            text-decoration: none;
            display: inline-block;
        }

        .btn-primary {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }

        .btn-primary:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(102, 126, 234, 0.3);
        }

        .btn-success {
            background: linear-gradient(135deg, #10b981 0%, #059669 100%);
            color: white;
        }

        .btn-success:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 20px rgba(16, 185, 129, 0.3);
        }

        .btn-group {
            display: flex;
            gap: 10px;
            margin-top: 30px;
        }

        .success-icon {
            font-size: 80px;
            text-align: center;
            margin-bottom: 20px;
        }

        .feature-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            margin: 30px 0;
        }

        .feature-item {
            padding: 15px;
            background: #f8f9fa;
            border-radius: 8px;
            border-left: 4px solid #10b981;
        }

        .feature-item strong {
            color: #1a1a1a;
            display: block;
            margin-bottom: 5px;
        }

        .feature-item small {
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🛍️ PyraStore</h1>
            <p>Amazon Affiliate Store - Automatic Installer</p>
        </div>

        <div class="installer-box">
            <!-- Progress Steps -->
            <div class="steps">
                <div class="step-item <?= $step == 1 ? 'active' : ($step > 1 ? 'completed' : '') ?>">
                    <div class="step-number">1</div>
                    <div>Requirements</div>
                </div>
                <div class="step-item <?= $step == 2 ? 'active' : ($step > 2 ? 'completed' : '') ?>">
                    <div class="step-number">2</div>
                    <div>Database</div>
                </div>
                <div class="step-item <?= $step == 3 ? 'active' : ($step > 3 ? 'completed' : '') ?>">
                    <div class="step-number">3</div>
                    <div>Configuration</div>
                </div>
                <div class="step-item <?= $step == 4 ? 'active' : '' ?>">
                    <div class="step-number">4</div>
                    <div>Complete</div>
                </div>
            </div>

            <div class="content">
                <?php if (!empty($errors)): ?>
                    <div class="alert alert-error">
                        <strong>❌ Error:</strong><br>
                        <?php foreach ($errors as $error): ?>
                            • <?= htmlspecialchars($error) ?><br>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <?php if ($step == 1): ?>
                    <!-- Step 1: System Requirements -->
                    <h2>System Requirements Check</h2>
                    <p>Let's make sure your server meets all requirements</p>

                    <h3 style="margin-top: 30px; margin-bottom: 15px; color: #1a1a1a;">PHP Extensions</h3>
                    <ul class="requirements-list">
                        <?php foreach ($requirements as $name => $status): ?>
                        <li>
                            <span><?= $name ?></span>
                            <span class="status-badge <?= $status ? 'success' : 'error' ?>">
                                <?= $status ? '✓ Installed' : '✗ Missing' ?>
                            </span>
                        </li>
                        <?php endforeach; ?>
                    </ul>

                    <h3 style="margin-top: 30px; margin-bottom: 15px; color: #1a1a1a;">Directory Permissions</h3>
                    <ul class="requirements-list">
                        <?php foreach ($writableDirectories as $dir => $status): ?>
                        <li>
                            <span><?= $dir ?></span>
                            <span class="status-badge <?= $status ? 'success' : 'error' ?>">
                                <?= $status ? '✓ Writable' : '✗ Not Writable' ?>
                            </span>
                        </li>
                        <?php endforeach; ?>
                    </ul>

                    <?php
                    $allPassed = !in_array(false, $requirements) && !in_array(false, $writableDirectories);
                    ?>

                    <?php if (!$allPassed): ?>
                        <div class="alert alert-error">
                            <strong>⚠️ Requirements Not Met</strong><br>
                            Please fix the issues above before continuing.
                        </div>
                    <?php else: ?>
                        <div class="alert alert-success">
                            <strong>✅ All Requirements Met!</strong><br>
                            Your server is ready for installation.
                        </div>
                    <?php endif; ?>

                    <div class="btn-group">
                        <a href="install.php?step=2" class="btn btn-primary" <?= !$allPassed ? 'style="opacity:0.5; pointer-events:none;"' : '' ?>>
                            Continue to Database Setup →
                        </a>
                    </div>

                <?php elseif ($step == 2): ?>
                    <!-- Step 2: Database Configuration -->
                    <h2>Database Configuration</h2>
                    <p>Enter your MySQL database details</p>

                    <form method="POST">
                        <div class="form-group">
                            <label>Database Host</label>
                            <input type="text" name="db_host" value="localhost" required>
                            <small>Usually "localhost" for most hosting providers</small>
                        </div>

                        <div class="form-group">
                            <label>Database Name</label>
                            <input type="text" name="db_name" value="pyrastore_db" required>
                            <small>The database will be created automatically if it doesn't exist</small>
                        </div>

                        <div class="form-group">
                            <label>Database Username</label>
                            <input type="text" name="db_user" required>
                            <small>Your MySQL username from cPanel</small>
                        </div>

                        <div class="form-group">
                            <label>Database Password</label>
                            <input type="password" name="db_pass" required>
                            <small>Your MySQL password</small>
                        </div>

                        <div class="alert alert-warning">
                            <strong>📌 Note:</strong> Make sure you have created a MySQL database and user in your cPanel before proceeding.
                        </div>

                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">
                                Install Database & Continue →
                            </button>
                        </div>
                    </form>

                <?php elseif ($step == 3): ?>
                    <!-- Step 3: Site Configuration -->
                    <h2>Site Configuration</h2>
                    <p>Configure your site and admin account</p>

                    <form method="POST">
                        <h3 style="margin-top: 30px; margin-bottom: 15px; color: #1a1a1a;">Site Settings</h3>

                        <div class="form-group">
                            <label>Site URL</label>
                            <input type="url" name="site_url" value="<?= (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['PHP_SELF']) ?>" required>
                            <small>Your site's full URL (without trailing slash)</small>
                        </div>

                        <div class="form-group">
                            <label>Amazon Affiliate ID</label>
                            <input type="text" name="affiliate_id" value="pyrastore-21" required>
                            <small>Your Amazon Associates tracking ID (e.g., yourstore-21)</small>
                        </div>

                        <h3 style="margin-top: 30px; margin-bottom: 15px; color: #1a1a1a;">Admin Account</h3>

                        <div class="form-group">
                            <label>Admin Username</label>
                            <input type="text" name="admin_username" value="admin" required>
                            <small>Choose a unique username for security</small>
                        </div>

                        <div class="form-group">
                            <label>Admin Password</label>
                            <input type="password" name="admin_password" required minlength="6">
                            <small>At least 6 characters. Use a strong password!</small>
                        </div>

                        <div class="form-group">
                            <label>Admin Email</label>
                            <input type="email" name="admin_email" required>
                            <small>Your email address</small>
                        </div>

                        <div class="alert alert-warning">
                            <strong>🔒 Important:</strong> Remember your admin credentials! You'll need them to access the admin panel.
                        </div>

                        <div class="btn-group">
                            <button type="submit" class="btn btn-success">
                                Complete Installation ✓
                            </button>
                        </div>
                    </form>

                <?php elseif ($step == 4): ?>
                    <!-- Step 4: Installation Complete -->
                    <div class="success-icon">🎉</div>
                    <h2 style="text-align: center;">Installation Complete!</h2>
                    <p style="text-align: center;">Your PyraStore is ready to go</p>

                    <div class="alert alert-success">
                        <strong>✅ Successfully Installed!</strong><br>
                        All files, database, and configurations have been set up properly.
                    </div>

                    <div class="feature-grid">
                        <div class="feature-item">
                            <strong>✓ Database Created</strong>
                            <small>All tables and sample data imported</small>
                        </div>
                        <div class="feature-item">
                            <strong>✓ Admin Account Ready</strong>
                            <small>Login credentials configured</small>
                        </div>
                        <div class="feature-item">
                            <strong>✓ 8 Categories Added</strong>
                            <small>Pre-configured with icons</small>
                        </div>
                        <div class="feature-item">
                            <strong>✓ Settings Configured</strong>
                            <small>Affiliate ID and site settings saved</small>
                        </div>
                    </div>

                    <h3 style="margin-top: 30px; margin-bottom: 15px; color: #1a1a1a;">Next Steps:</h3>
                    <ol style="line-height: 2; color: #666;">
                        <li><strong>Delete install.php</strong> - For security, delete this file from your server</li>
                        <li><strong>Login to Admin</strong> - Access your admin panel and start adding products</li>
                        <li><strong>Configure Tracking</strong> - Add your Google Analytics, Meta Pixel, and TikTok Pixel IDs</li>
                        <li><strong>Add Products</strong> - Start adding Amazon products with your affiliate links</li>
                        <li><strong>Customize Settings</strong> - Update site name, contact info, and other settings</li>
                    </ol>

                    <div class="alert alert-warning" style="margin-top: 30px;">
                        <strong>⚠️ Security Warning:</strong><br>
                        Please delete or rename <code>install.php</code> to prevent unauthorized reinstallation.
                    </div>

                    <div class="btn-group" style="margin-top: 30px;">
                        <a href="admin/login.php" class="btn btn-primary">
                            🔐 Go to Admin Panel
                        </a>
                        <a href="index.php" class="btn btn-success">
                            🛍️ View Your Store
                        </a>
                    </div>

                    <div style="text-align: center; margin-top: 40px; padding-top: 30px; border-top: 2px solid #e0e0e0;">
                        <p style="color: #999; font-size: 14px;">
                            Thank you for choosing PyraStore!<br>
                            <strong>Happy Selling! 🚀💰</strong>
                        </p>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</body>
</html>
